$(OBJDIR)/class_initialize.o: class_initialize.cpp
	$(CPP_COMPILE)
$(OBJDIR)/class_loader.o: class_loader.cpp
	$(CPP_COMPILE)
$(OBJDIR)/class_parse.o: class_parse.cpp
	$(CPP_COMPILE)
$(OBJDIR)/class_prepare.o: class_prepare.cpp
	$(CPP_COMPILE)
$(OBJDIR)/class_table.o: class_table.cpp
	$(CPP_COMPILE)
$(OBJDIR)/class_verify.o: class_verify.cpp
	$(CPP_COMPILE)
$(OBJDIR)/class_utils.o: class_utils.cpp
	$(CPP_COMPILE)
$(OBJDIR)/method.o: method.cpp
	$(CPP_COMPILE)
$(OBJDIR)/string_pool.o: string_pool.cpp
	$(CPP_COMPILE)
$(OBJDIR)/vm_interface.o: vm_interface.cpp
	$(CPP_COMPILE)
